### ISSUE TITLE
Where are the other Scenario sources?

### ISSUE THREAD

**Issue by ozdanborne** [BenHall/katacoda-scenarios#2]
I see 22 collections of scenarios at https://www.katacoda.com/ben_hall 

But only 12 labs in this repository. 

- How do I get access to the source for the other scenarios?
- Are there any reference docs?
- Is there a way to see how other public scenarios were created? That is, a way to figure out which github repo is backing a particular demo?

More specifically, I'm trying to find a sample scenario that starts up multiple hosts. Can you point me to an example of how to do that?

**Comment by mohan08p** [comment]
@djosborne : me too searching for those scenario. :1234:

**Comment by BenHall** [comment]
It's great that you're both super keen to see what's happening under the covers!! 😺

I'm working on the new documentation and scenario process at the moment, it's just taking longer than expected to complete. Thank you for bearing with me. 

I will contact you both this afternoon with more details.

**Comment by kamsz** [comment]
I'm also interested :)

**Comment by BenHall** [comment]
The initial version of the docs site is online at https://katacoda.com/docs

We'll be working on releasing more examples and documentation over the coming weeks. Thanks for your support.
