### ISSUE TITLE
Problem in updating the tutorial

### ISSUE THREAD

**Issue by mohan08p** [BenHall/katacoda-scenarios#3]
Their is minor issues where the tutorial is not getting updated as per the requirements. 
e.g. I was trying to save the update, but the scenario is not saved and the updates are rejected by the scenario as shown in the figure below, **"Saving"** in progress...
![saving_issue](https://cloud.githubusercontent.com/assets/7372759/23546368/44878e06-0025-11e7-9252-8c38a570b195.png)

Kindly, guide look into the it. Thank you.

**Comment by BenHall** [comment]
Sorry for the delay, I noticed the errors and I'm looking into it now.

**Comment by BenHall** [comment]
Sorry for the delay, this has now been resolved.
